Repository ManageIQ/manageiq-providers-workflows, pull requests merged in 2023-07, with the labels that each got.

#5 Move workflow executing into manageiq-floe
  app/models/manageiq/providers/workflows/automation_manager/workflow.rb
  app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
  manageiq-providers-workflows.gemspec
  spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
  spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb
Labels: refactoring, petrosian/yes?

#33 Fix Workflows Credentials from Authentication options API
  app/models/manageiq/providers/workflows/automation_manager/credential.rb
  app/models/manageiq/providers/workflows/automation_manager/scm_credential.rb
  app/models/manageiq/providers/workflows/automation_manager/workflow_credential.rb
  spec/models/manageiq/providers/workflows/automation_manager/workflows_credential_spec.rb
Labels: bug, petrosian/yes?

#34 Fix workflows queued on embedded_ansible
  spec/models/manageiq/providers/workflows/automation_manager/configuration_script_source_spec.rb
Labels: bug, petrosian/yes?

#35 Fix WorkflowInstance#output not being set
  app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
  spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
Labels: bug, petrosian/yes?

#28 Set the Floe::Workflow::Runner based on platform
  config/initializers/floe_docker_runner.rb
  lib/manageiq/providers/workflows/engine.rb
Labels: enhancement, petrosian/yes

#36 Update GitHub Actions versions
  .github/workflows/ci.yaml
Labels: developer

#37 Fix the default role from automation to automate
  app/models/manageiq/providers/workflows/automation_manager/workflow.rb
  app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
  spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb
Labels: bug, petrosian/yes?

#38 Normalize the ae_result passed to after_ae_delivery
  app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
Labels: bug, petrosian/yes?
