Repository ManageIQ/manageiq-providers-workflows, pull requests merged in 2023-10, with the labels that each got.

#54 Bump floe to v0.4.1 for task output fixes
  manageiq-providers-workflows.gemspec
Labels: bug, quinteros/yes

#55 Pass the workflow service account
  lib/manageiq/providers/workflows/engine.rb
  manageiq-providers-workflows.gemspec
Labels: enhancement, quinteros/yes

#56 Fix issue where new service account ENV var is forced in every process
  lib/manageiq/providers/workflows/engine.rb
Labels: bug, quinteros/yes

#58 Drop Ruby 2.7
  .github/workflows/ci.yaml
Labels: dependencies
