Repository ManageIQ/manageiq-providers-workflows, pull requests merged in 2024-11, with the labels that each got.

#120 test with ruby 3.3
  .github/workflows/ci.yaml
Labels: ruby3.3

#121 Add object_type,_id to WorkflowInstance#run_queue
  app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
  lib/manageiq/providers/workflows/runner.rb
  spec/lib/manageiq/providers/workflows/runner_spec.rb
Labels: bug, radjabov/yes

#123 Fix floe bug with Parallel/Map on Kubernetes
  manageiq-providers-workflows.gemspec
Labels: bug, radjabov/yes?
