Repository ManageIQ/manageiq-providers-workflows, pull requests merged in 2024-08, with the labels that each got.

#107 Bump floe to v0.12.0
  app/models/manageiq/providers/workflows/automation_manager/workflow.rb
  app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
  manageiq-providers-workflows.gemspec
  spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
  spec/models/manageiq/providers/workflows/automation_manager/workflow_instance_spec.rb
Labels: dependencies, radjabov/yes?

#108 Use ruby 3.1 for code coverage
  .github/workflows/ci.yaml
Labels: developer, test

#105 Pass requester userid and email into workflows
  app/models/manageiq/providers/workflows/automation_manager/workflow.rb
  lib/manageiq/providers/workflows/builtin_methods.rb
  lib/manageiq/providers/workflows/builtin_runner.rb
  spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
  spec/lib/manageiq/providers/workflows/builtin_runner_spec.rb
Labels: enhancement

#112 Use workflow_instance manager_ref as Execution ID
  app/models/manageiq/providers/workflows/automation_manager/workflow.rb
  spec/models/manageiq/providers/workflows/automation_manager/workflow_spec.rb
Labels: enhancement

#113 Use WorkflowInstance#manager_ref and execution_id for events
  app/models/manageiq/providers/workflows/automation_manager/workflow_instance.rb
  lib/manageiq/providers/workflows/runner.rb
  manageiq-providers-workflows.gemspec
  spec/factories/workflow_instance.rb
  spec/lib/manageiq/providers/workflows/runner_spec.rb
Labels: enhancement, radjabov/yes?
