Repository ManageIQ/manageiq-providers-workflows, pull requests merged in 2024-05, with the labels that each got.

#82 Update to use Floe.register_scheme API
  lib/manageiq/providers/workflows/engine.rb
  manageiq-providers-workflows.gemspec
Labels: enhancement

#83 Workflow#run accepts context
  app/models/manageiq/providers/workflows/automation_manager/workflow.rb
Labels: enhancement

#84 Move checking builtin method status into Methods
  lib/manageiq/providers/workflows/builtin_methods.rb
  lib/manageiq/providers/workflows/builtin_runner.rb
Labels: refactoring

#85 pass object to workflow instance
  app/models/manageiq/providers/workflows/automation_manager/workflow.rb
Labels: enhancement

#87 Some minor refactorings to BuiltinMethods / BuiltinRunner
  lib/manageiq/providers/workflows/builtin_methods.rb
  lib/manageiq/providers/workflows/builtin_runner.rb
Labels: refactoring

#81 Add builtin method: provision_execute
  lib/manageiq/providers/workflows/builtin_methods.rb
  lib/manageiq/providers/workflows/builtin_runner.rb
Labels: enhancement, unmergeable

#89 Add specs for BuiltinMethods
  lib/manageiq/providers/workflows/builtin_methods.rb
  lib/manageiq/providers/workflows/builtin_result_mixin.rb
  lib/manageiq/providers/workflows/builtin_runner.rb
  spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
  spec/lib/manageiq/providers/workflows/builtin_runner_spec.rb
Labels: bug

#91 Fix BuiltinMethods.miq_request_task_status!
  lib/manageiq/providers/workflows/builtin_methods.rb
Labels: bug

#90 [WIP] Fix error!/success! calls from BuiltinMethods
  lib/manageiq/providers/workflows/builtin_methods.rb
  lib/manageiq/providers/workflows/builtin_result_mixin.rb
  lib/manageiq/providers/workflows/builtin_runner.rb
Labels: wip, unmergeable

#93 Fix BuiltinMethods.email task status spec
  spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
Labels: bug, test

#94 automatically update options for provisioning requests
  lib/manageiq/providers/workflows/builtin_methods.rb
  spec/lib/manageiq/providers/workflows/builtin_methods_spec.rb
Labels: enhancement, radjabov/yes?

#95 Fail seeding on invalid out of the box workflows.
  app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
Labels: enhancement
