Repository ManageIQ/manageiq-providers-workflows, pull requests merged in 2024-03, with the labels that each got.

#72 Update codeclimate channel to the latest in manageiq-style
  .codeclimate.yml
Labels: dependencies

#57 Seed workflows from plugins' content/workflows
  app/models/manageiq/providers/workflows/automation_manager/configuration_script_source.rb
  config/settings.yml
  lib/manageiq/providers/workflows/engine.rb
Labels: enhancement

#75 Add Settings.ems.ems_workflows.runner
  config/settings/development.yml
  lib/manageiq/providers/workflows/engine.rb
Labels: enhancement, developer
